### ISSUE TITLE
Errores vistos en la revisión preliminar

### ISSUE THREAD

**Issue by jlcmes** [rsgp229-dam-davinci/ExamenMayoV1#1]
Comentarios, por favor añádelos.

Método guardarEnBaseDeDatos no revisa que tipo de Libro le llega, por lo que no puedes guardar los datos específicos de cada uno. Prueba con la instrucción instance of y determinas el tipo para poder guardar más información, no sólo titulo y autor.
Revisa SQLExceptions antes de Exception, ojo con usar el Exception a lo loco.

No entiendo para qué tienes el setTamanioArchivo si controlas la ya el constructor define todo. Idem para el libro impreso.

Ojo que dejaste los credenciales públicos en src/main/resources/database.properties
Ponlo en el gitignore y borralo para la siguiente vez.
 
Usas src/test/java/dam/davinci/BibliotecaTest.java para los test, pero no prefieres ponerlo en el main y reservas ese archivo para pruebas más exhaustivas?

Good job overall!

**Comment by rsgp229-dam-davinci** [comment]
> Comentarios, por favor añádelos.
En curso
> 
> Método guardarEnBaseDeDatos no revisa que tipo de Libro le llega, por lo que no puedes guardar los datos específicos de cada uno. Prueba con la instrucción instance of y determinas el tipo para poder guardar más información, no sólo titulo y autor. 
Qué sería más correcto? Dos tablas para cada tipo o una tabla con las propiedades de todos los tipos?

Revisa SQLExceptions antes de Exception, ojo con usar el Exception a lo loco.
En curso
> 
> No entiendo para qué tienes el setTamanioArchivo si controlas la ya el constructor define todo. Idem para el libro impreso.
> 
> Ojo que dejaste los credenciales públicos en src/main/resources/database.properties Ponlo en el gitignore y borralo para la siguiente vez.
Correcto, lo he dejado a propósito para que se pueda comprobar que funciona, Las credenciales o la cuenta la borraré pasado un tiempo.
> 
> Usas src/test/java/dam/davinci/BibliotecaTest.java para los test, pero no prefieres ponerlo en el main y reservas ese archivo para pruebas más exhaustivas?
Hacer pruebas más exhaustivas, estoy de acuerdo. Lo del main es lo que no entiendo; hacer pruebas en el main?
> 
> Good job overall!

**Comment by rsgp229-dam-davinci** [comment]
Se han añadido los comentarios (javadoc) y algún otro comentario aclaratorio

**Comment by rsgp229-dam-davinci** [comment]
Se ha modificado la tabla de la base de datos para que incorpore los campos 'pages' y ' mb_size' para guardar la información de los subtipos de la clase Libro.
Se ha modificado el método guardarEnBaseDeDatos. Ahora el método discrimina los subtipos de la clase Libro y guarda en la base de datos en función del libro recibido.

**Comment by rsgp229-dam-davinci** [comment]
Se ha modificado el manejo de excepciones en el método guardarEnBaseDeDatos.
Se han añadido clausulas para diferenciar cada tipo de excepción e informar adecuadamente.
